# Generated by Django 3.2.7 on 2021-09-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinput',
            name='send_date',
        ),
    ]
