# Generated by Django 3.2.7 on 2021-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_userinput_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessage',
            name='botmessage_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinput',
            name='userinput_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
