# Generated by Django 3.2.7 on 2021-09-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20210924_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='botmessage',
            name='user',
            field=models.CharField(default='gaby', max_length=255),
        ),
        migrations.AddField(
            model_name='userinput',
            name='user',
            field=models.CharField(default='gaby', max_length=255),
            preserve_default=False,
        ),
    ]
