# Generated by Django 3.2.7 on 2021-09-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_budget'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
