# Generated by Django 3.2.7 on 2021-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('Dining', 'Dining'), ('Groceries', 'Groceries'), ('Bill', 'Bill'), ('Transport', 'Transport'), ('Shopping', 'Shopping'), ('Others', 'Others')], default='Others', max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('user', models.CharField(max_length=255)),
            ],
        ),
    ]
